openapi: 3.0.0
info:
  # title: HNG 360 Skills Evaluation API
  title: Skills Evaluation API
  description: |-
    This is a simple RESTful API for 360 skills evaluation Server based on the OpenAPI 3.0 specification. 
    You can find all the api endpoints
  version: 0.1.0

servers:
  - url: http://localhost:8000/api
    description: local server
  - url: http://producation.app/api
    description: production server
tags:
  - name: auth
    description: Everything about your Authentication
components:
  schemas:
    GeneralError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
api_key: []          
paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: User Login.
      parameters:
        - name: email
          in: path
          description: registered email
          required: true
          schema:
            type: string
        - name: password
          in: path
          description: User Password
          required: true          
          schema:
            type: string
            format: password
      responses:
        '200': 
          description: A JSON array of user details
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /user:
    get:
      tags:
        - auth
      summary: Returns logged in user.
      responses:
        '200': 
          description: A JSON array of user details
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
      securitySchemes:
        api_key:
          type: apiKey
          name: api_key
          in: header